spring:
  application:
    name: regenwormen

  datasource:
    url: jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres
    username: postgres.wxdfnqxpahfbhaxyrntk
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: dev

server:
  port: 8080

spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 20MB
