spring:
  application:
    name: regenwormen

  datasource:
    url: jdbc:postgresql://db.wxdfnqxpahfbhaxyrntk.supabase.co:5432/postgres
    username: postgres
    password: regenwormen

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 20MB
