spring:
  application:
    name: regenwormen

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:6543/postgres
    username: postgres.wxdfnqxpahfbhaxyrntk
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      data-source-properties:
        prepareThreshold: 0   # BELANGRIJK voor transaction pooler

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: dev

server:
   port: ${PORT:8080}
