spring:
  datasource:
    url: jdbc:postgresql://db.wxdfnqxpahfbhaxyrntk.supabase.co:5432/postgres
    username: postgres
    password: regenwormen
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
